SGL (Simple Graph Library): SGL::Adjacency_Matrix< T > Class Template Reference
SGL::Adjacency_Matrix< T > Class Template Reference
Class representing an adjacency matrix for internal use by a graph.
#include <AdjacencyMatrix.h>
Classes
class DirectedMatrix
class IMatrix
class UndirectedMatrix
Public Member Functions
Adjacency_Matrix (configuration p_f=0)
Constructor.
Adjacency_Matrix (const Adjacency_Matrix &)
Copy constructor.
~Adjacency_Matrix ()
Adjacency_Matrix & operator= (const Adjacency_Matrix &)
Assignment operator overloading.
unsigned nbVertices () const
Returns the number of vertices in the matrix.
unsigned nbEdges () const
Returns the number of edges in the list.
unsigned int order () const
Alias of the nbVertices method "order" is the mathematical term for "number of vertices".
unsigned int size () const
Alias of the nbEdges method "size" is the mathematical term for "number of edges" (not to be mistaken with order, the number of vertices)
bool hasVertex (const T &) const
verifies that a vertex is in the matrix
bool vertexIsSource (const T &) const
Tells if a vertex is a source (no edges coming to it = in-degree 0)
bool vertexIsSink (const T &) const
Tells if a vertex is a sink (no edges starting from it = out-degree = 0)
unsigned vertexInDegree (const T &) const
Returns the in-degree of a vertex in the matrix i.e.
unsigned vertexOutDegree (const T &) const
Returns the out-degree of a vertex in the graph, i.e.
std::vector< T > vertexNeighborhood (const T &, bool p_closed=false) const
Lists the adjacent vertices of a vertex in the graph.
std::vector< T > vertices () const
Lists all the vertices in the graph Returns in a vector all the vertices of the graph.
bool hasEdge (const T &, const T &) const
verifies that an edge is in the matrix
std::vector< std::pair< T, T > > edges () const
Lists all the edges in the graph.
void addVertex (const T &)
Adds a vertex to the graph.
void deleteVertex (const T &)
deletes a vertex from the graph
void addEdge (const T &, const T &)
Adds an edge in the graph.
void deleteEdge (const T &, const T &)
Deletes an edge in the graph.
bool operator== (const Adjacency_Matrix &p_rhs) const
Checks the structural equality of two matrices.
Public Member Functions inherited from SGL::AbstractGraph< T >
virtual ~AbstractGraph ()
bool equals (const AbstractGraph &p_other) const
Checks the structural equality of the current graph with another (same vertices, same edges)
bool operator== (const AbstractGraph &p_g2)
Overloads the == operator to check structural equality of two graphs.
Private Member Functions
unsigned _index (const T &p_v) const
Private function used to retrieve the index in the intern adjacency list of an element.
const std::string _repr () const
Output function.
Private Attributes
std::vector< T > m_elems
IMatrix * m_matrix
Friends
std::ostream & operator<< (std::ostream &p_stream, const Adjacency_Matrix &p_matrix)
Additional Inherited Members
Protected Attributes inherited from SGL::AbstractGraph< T >
int m_config
unsigned m_nbVertices
Detailed Description
template<typename T>
class SGL::Adjacency_Matrix< T >
Class representing an adjacency matrix for internal use by a graph.
Definition at line 29 of file AdjacencyMatrix.h.
Constructor & Destructor Documentation
template<typename T > SGL::Adjacency_Matrix< T >::Adjacency_Matrix (configuration p_f = 0)
Constructor.
Parameters
[in] p_f the bitwise-or'd configuration flags given to the constructor. One important configuration is UNDIRECTED or not : it changes the type of the internal matrix.
Postcondition
The current graph is initialized with the given configuration
Exceptions
bad_alloc in case of insufficient memory
Definition at line 29 of file AdjacencyMatrix.hpp.
References SGL::UNDIRECTED.
{
     this->m_config = p_f;
     this->m_nbVertices = 0;
     if (p_f & UNDIRECTED) {
         m_matrix = new UndirectedMatrix();
     } else {
         m_matrix = new DirectedMatrix();
     }
 }
template<typename T > SGL::Adjacency_Matrix< T >::Adjacency_Matrix (const Adjacency_Matrix< T > & p_src)
Copy constructor.
Parameters
[in] p_src the source graph that will be copied
Postcondition
The current graph is initialized with the same data as the source
Exceptions
bad_alloc in case of insufficient memory
Definition at line 46 of file AdjacencyMatrix.hpp.
References SGL::Adjacency_Matrix< T >::addEdge(), SGL::Adjacency_Matrix< T >::addVertex(), SGL::Adjacency_Matrix< T >::edges(), SGL::AbstractGraph< T >::m_config, SGL::Adjacency_Matrix< T >::m_matrix, SGL::UNDIRECTED, and SGL::Adjacency_Matrix< T >::vertices().
                                                                       :
         m_matrix(NULL) {
     this->m_config = p_src.m_config;
     if (this->m_config & UNDIRECTED) {
         m_matrix = new UndirectedMatrix();
     } else {
         m_matrix = new DirectedMatrix();
     }
     vector<T> vertices = p_src.vertices();
     // add the vertices
     for (unsigned i = 0; i < vertices.size(); i++) {
         addVertex(vertices[i]);
     }
     // add the edges
     vector<pair<T, T> > edges = p_src.edges();
     for (unsigned pos = 0; pos < edges.size(); pos++) {
         addEdge(edges[pos].first, edges[pos].second);
     }
 }
template<typename T> SGL::Adjacency_Matrix< T >::~Adjacency_Matrix () inline
Definition at line 36 of file AdjacencyMatrix.h.
References SGL::Adjacency_Matrix< T >::m_matrix.
 { delete m_matrix; }
Member Function Documentation
template<typename T > unsigned SGL::Adjacency_Matrix< T >::_index (const T & p_v) const private
Private function used to retrieve the index in the intern adjacency list of an element.
Precondition
The vertex is in the graph
Parameters
[in] p_v the vertex to search
Exceptions
logic_error the vertex isn't in the graph
Returns
the index in the adjacency list of the given vertex's node
Definition at line 432 of file AdjacencyMatrix.hpp.
{
     for (unsigned pos = 0; pos < m_elems.size(); pos++) {
         if (m_elems[pos] == p_v) {
             return pos;
         }
     }
     throw logic_error("Vertex not in the graph");
 }
template<typename T > const string SGL::Adjacency_Matrix< T >::_repr () const private virtual
Output function.
Implements SGL::AbstractGraph< T >.
Definition at line 399 of file AdjacencyMatrix.hpp.
{
     stringstream stream;
 //
 //  stream << "Matrix vertices number: " << nbVertices() << endl;
 //  stream << "Matrix edges number: " << nbEdges() << endl;
 //  stream << "Matrix composition:" << endl;
 //  if (nbVertices() == 0) {
 //      stream << "null";
 //  } else {
 //      stream << "\t";
 //  }
 //  for (unsigned i = 0; i < m_elems.size(); i++) {
 //      stream << m_elems[i] << "\t";
 //  }
 //  stream << endl;
 //  for (unsigned i = 0; i < m_matrix.size(); i++) {
 //      stream << m_elems[i] << "\t";
 //      for (unsigned j = 0; j < m_matrix[i].size(); j++) {
 //          stream << m_matrix[i][j] << "\t";
 //      }
 //      stream << endl;
 //  }
     return stream.str();
 }
template<typename T > void SGL::Adjacency_Matrix< T >::addEdge (const T & p_v1, const T & p_v2) virtual
Adds an edge in the graph.
Parameters
[in] p_v1 the source vertex of the edge
[in] p_v2 the destination vertex of the edge
Precondition
Enough memory available
The 2 vertices of the edge are in the graph
Postcondition
The graph counts one more edge
Exceptions
bad_alloc in case of insufficient memory
logic_error if one of the two vertices isn't in the graph
logic_error if the edge already exists
Implements SGL::AbstractGraph< T >.
Definition at line 303 of file AdjacencyMatrix.hpp.
Referenced by SGL::Adjacency_Matrix< T >::Adjacency_Matrix().
{
     int index_s1, index_s2;
     try {
         index_s1 = _index(p_v1);
         index_s2 = _index(p_v2);
     } catch (const logic_error &le) {
         throw logic_error("addEdge: one of the vertices isn't in the graph");
     }
     if (m_matrix->hasEdge(index_s1, index_s2)) {
         throw logic_error("addEdge: this edge already exists");
     }
     m_matrix->addEdge(index_s1, index_s2);
 }
template<typename T > void SGL::Adjacency_Matrix< T >::addVertex (const T & p_elem) virtual
Adds a vertex to the graph.
Parameters
[in] p_elem the new element to put in the graph
Precondition
Enough memory available
The vertex isn't already in the graph
Postcondition
The graph counts one more vertex
Exceptions
bad_alloc in case of insufficient memory
logic_error if the vertex already is in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 261 of file AdjacencyMatrix.hpp.
Referenced by SGL::Adjacency_Matrix< T >::Adjacency_Matrix().
{
     if (hasVertex(p_elem)) {
         throw logic_error("addVertex: this element already is a vertex");
     }
     m_elems.push_back(p_elem);
     m_matrix->addVertex();
     this->m_nbVertices++;
 }
template<typename T > void SGL::Adjacency_Matrix< T >::deleteEdge (const T & p_v1, const T & p_v2) virtual
Deletes an edge in the graph.
Parameters
[in] p_v1 the source vertex of the edge
[in] p_v2 the destination vertex of the edge
Precondition
The 2 vertices of the edge are in the graph
Postcondition
The graph counts one less edge
Exceptions
logic_error if one of the two vertices isn't in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 326 of file AdjacencyMatrix.hpp.
{
     int index_s1, index_s2;
     try {
         index_s1 = _index(p_v1);
         index_s2 = _index(p_v2);
     } catch (const logic_error &le) {
         throw logic_error("deleteEdge: one of the vertices isn't in the graph");
     }
     if (!m_matrix->hasEdge(index_s1, index_s2)) {
         throw logic_error("deleteEdge: no edge between the two vertices");
     }
     m_matrix->deleteEdge(index_s1, index_s2);
 }
template<typename T > void SGL::Adjacency_Matrix< T >::deleteVertex (const T & p_v) virtual
deletes a vertex from the graph
Parameters
[in] p_v The element we want to delete the vertex of
Precondition
The vertex is in the graph
Postcondition
The graph counts one less vertex
Exceptions
logic_error if the vertex isn't in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 278 of file AdjacencyMatrix.hpp.
{
     int index_s;
     try {
         index_s = _index(p_v);
     } catch (const logic_error &le) {
         throw logic_error("deleteVertex: the vertex isn't in the graph");
     }
     this->m_matrix->deleteVertex(index_s);
     m_elems.erase(m_elems.begin() + index_s);
     this->m_nbVertices--;
 }
template<typename T > vector< pair< T, T > > SGL::Adjacency_Matrix< T >::edges () const virtual
Lists all the edges in the graph.
Returns all the edges under the form of a vector of pair of elements (source, destination)
Precondition
Enough memory available
Postcondition
A vector of all the edges is returned
Exceptions
bad_alloc in case of insufficient memory
Returns
A vector of pairs of elements organized as (source, destination)
Implements SGL::AbstractGraph< T >.
Definition at line 364 of file AdjacencyMatrix.hpp.
Referenced by SGL::Adjacency_Matrix< T >::Adjacency_Matrix(), and SGL::Adjacency_Matrix< T >::operator==().
{
     vector<pair<T, T> > edges;
     vector<vector<int> > edge_indexes;
     m_matrix->edges(edge_indexes);
     for (unsigned src = 0; src < edge_indexes.size(); src++) {
         vector<pair<T, T> > vertex_edges;
         for (unsigned dest = 0; dest < edge_indexes[src].size(); dest++) {
             edges.push_back(make_pair(m_elems[src], m_elems[edge_indexes[src][dest]]));
         }
     }
     return edges;
 }
template<typename T > bool SGL::Adjacency_Matrix< T >::hasEdge (const T & p_v1, const T & p_v2) const virtual
verifies that an edge is in the matrix
Parameters
[in] p_v1 the source vertex of the edge
[in] p_v2 the destination vertex of the edge
Precondition
The 2 vertices of the edge are in the matrix
Exceptions
logic_error if one of the two vertices isn't in the matrix
Returns
whether the matrix contains this edge or not
Implements SGL::AbstractGraph< T >.
Definition at line 110 of file AdjacencyMatrix.hpp.
{
     int index_s1, index_s2;
     try {
         index_s1 = _index(p_v1);
         index_s2 = _index(p_v2);
     } catch (const logic_error &le) {
         throw logic_error("hasEdge: one of the vertices isn't in the matrix");
     }
     return (m_matrix->hasEdge(index_s1, index_s2));
 }
template<typename T > bool SGL::Adjacency_Matrix< T >::hasVertex (const T & p_v) const virtual
verifies that a vertex is in the matrix
Parameters
[in] p_v the element we search the vertex of
Returns
whether the matrix contains this vertex or not
Implements SGL::AbstractGraph< T >.
Definition at line 90 of file AdjacencyMatrix.hpp.
{
     bool isHere = true;
     try {
         _index(p_v);
     } catch (const logic_error &le) {
         isHere = false;
     }
     return isHere;
 }
template<typename T> unsigned SGL::Adjacency_Matrix< T >::nbEdges () const inline virtual
Returns the number of edges in the list.
Returns
the number of edges in the list
Implements SGL::AbstractGraph< T >.
Definition at line 52 of file AdjacencyMatrix.h.
References SGL::Adjacency_Matrix< T >::m_matrix, and SGL::Adjacency_Matrix< T >::IMatrix::nbEdges().
Referenced by SGL::Adjacency_Matrix< T >::UndirectedMatrix::nbEdges(), SGL::Adjacency_Matrix< T >::operator==(), and SGL::Adjacency_Matrix< T >::size().
 { return m_matrix->nbEdges(); }
template<typename T> unsigned SGL::Adjacency_Matrix< T >::nbVertices () const inline virtual
Returns the number of vertices in the matrix.
Returns
the number of vertices in the matrix
Implements SGL::AbstractGraph< T >.
Definition at line 46 of file AdjacencyMatrix.h.
References SGL::AbstractGraph< T >::m_nbVertices.
Referenced by SGL::Adjacency_Matrix< T >::UndirectedMatrix::_nbVertices(), SGL::Adjacency_Matrix< T >::operator==(), and SGL::Adjacency_Matrix< T >::order().
 { return this->m_nbVertices; }
template<typename T > Adjacency_Matrix< T > & SGL::Adjacency_Matrix< T >::operator= (const Adjacency_Matrix< T > & p_src)
Assignment operator overloading.
Parameters
[in] p_src the source graph that will be copied
Postcondition
The current graph is initialized with the same data as the source
Exceptions
bad_alloc in case of insufficient memory
Returns
the current class returns itself
Definition at line 74 of file AdjacencyMatrix.hpp.
References SGL::AbstractGraph< T >::m_config, SGL::Adjacency_Matrix< T >::m_elems, SGL::Adjacency_Matrix< T >::m_matrix, and SGL::AbstractGraph< T >::m_nbVertices.
{
     Adjacency_Matrix<T> copy(p_src);
     this->m_config = p_src.m_config;
     this->m_nbVertices = p_src.m_nbVertices;
     std::swap(m_elems, copy.m_elems);
     std::swap(m_matrix, copy.m_matrix);
     return (*this);
 }
template<typename T > bool SGL::Adjacency_Matrix< T >::operator== (const Adjacency_Matrix< T > & p_rhs) const
Checks the structural equality of two matrices.
Parameters
[in] p_rhs the graph we want to compare the current one to
Returns
true if the matrices are identical, else false
Definition at line 384 of file AdjacencyMatrix.hpp.
References SGL::Adjacency_Matrix< T >::edges(), SGL::Adjacency_Matrix< T >::nbEdges(), SGL::Adjacency_Matrix< T >::nbVertices(), and SGL::Adjacency_Matrix< T >::vertices().
{
     bool areEqual = true;
     // first check number of edges/vertices
     areEqual = (nbEdges() == p_rhs.nbEdges() || nbVertices() == p_rhs.nbVertices());
     // then check that vertices and edges are the same (don't do it if one of the first checks was already wrong)
     if (areEqual) {
         areEqual = (vertices() == p_rhs.vertices() && edges() == p_rhs.edges());
     }
     return areEqual;
 }
template<typename T> unsigned int SGL::Adjacency_Matrix< T >::order () const inline virtual
Alias of the nbVertices method "order" is the mathematical term for "number of vertices".
Returns
the number of vertices in the list
Implements SGL::AbstractGraph< T >.
Definition at line 59 of file AdjacencyMatrix.h.
References SGL::Adjacency_Matrix< T >::nbVertices().
 { return nbVertices(); }
template<typename T> unsigned int SGL::Adjacency_Matrix< T >::size () const inline virtual
Alias of the nbEdges method "size" is the mathematical term for "number of edges" (not to be mistaken with order, the number of vertices)
Returns
the number of edges in the list
Implements SGL::AbstractGraph< T >.
Definition at line 66 of file AdjacencyMatrix.h.
References SGL::Adjacency_Matrix< T >::nbEdges().
 { return nbEdges(); }
template<typename T > unsigned SGL::Adjacency_Matrix< T >::vertexInDegree (const T & p_v) const virtual
Returns the in-degree of a vertex in the matrix i.e.
the number of neighbor vertices of this vertex which have an edge that goes to it.
Parameters
[in] p_v the vertex we want to know the in-degree of
Precondition
The vertex has to be in the matrix
Exceptions
logic_error if the vertex isn't in the matrix
Returns
the number of edges to other vertices the vertex is the destination of
Implements SGL::AbstractGraph< T >.
Definition at line 132 of file AdjacencyMatrix.hpp.
References SGL::UNDIRECTED.
{
     unsigned index_s;
     unsigned indegree = 0;
     try {
         index_s = _index(p_v);
     } catch (const logic_error &le) {
         throw logic_error("vertexInDegree: the vertex isn't in the graph");
     }
     for (unsigned i = 0; i < m_elems.size(); i++) {
         if (m_matrix->hasEdge(i, index_s)) {
             indegree++;
             // if the graph is undirected: a loop counts twice
             if (i == index_s && (this->m_config & UNDIRECTED)) {
                 indegree++;
             }
         }
     }
     return indegree;
 }
template<typename T > bool SGL::Adjacency_Matrix< T >::vertexIsSink (const T & p_v) const virtual
Tells if a vertex is a sink (no edges starting from it = out-degree = 0)
Precondition
The graph must be directed
Parameters
[in] p_v the vertex element we want to know whether it's a sink or not
Exceptions
logic_error if the function is called with an undirected graph
Returns
(boolean) whether the vertex is a sink or not
Implements SGL::AbstractGraph< T >.
Definition at line 206 of file AdjacencyMatrix.hpp.
References SGL::UNDIRECTED.
{
     // no such thing as a source in an undirected graph (as the edges are undirected, they don't "come to" any vertex)
     if (this->m_config & UNDIRECTED) {
         throw logic_error("vertexIsSource: the graph is undirected");
     }
     return (vertexOutDegree(p_v) == 0);
 }
template<typename T > bool SGL::Adjacency_Matrix< T >::vertexIsSource (const T & p_v) const virtual
Tells if a vertex is a source (no edges coming to it = in-degree 0)
Precondition
The graph must be directed
Parameters
[in] p_v the vertex element we want to know whether it's a source or not
Exceptions
logic_error if the function is called with an undirected graph
Returns
(boolean) whether the vertex is a source or not
Implements SGL::AbstractGraph< T >.
Definition at line 190 of file AdjacencyMatrix.hpp.
References SGL::UNDIRECTED.
{
     // no such thing as a source in an undirected graph (as the edges are undirected, they don't "come from" any vertex)
     if (this->m_config & UNDIRECTED) {
         throw logic_error("vertexIsSource: the graph is undirected");
     }
     return (vertexInDegree(p_v) == 0);
 }
template<typename T > vector< T > SGL::Adjacency_Matrix< T >::vertexNeighborhood (const T & p_v, bool p_closed = false) const virtual
Lists the adjacent vertices of a vertex in the graph.
If closed boolean is set to true, the vertex itself will be included in the returned neighborhood, making it a closed neighborhood (as opposed to the open version, without it included).
Parameters
[in] p_v the vertex we want the neighborhood of
[in] p_closed boolean to say whether we want the closed neighborhood of the vertex or not (false by default)
Precondition
Enough memory available
The vertex has to be in the graph
Exceptions
bad_alloc in case of insufficient memory
logic_error if the vertex isn't in the graph
Returns
A vector containing the data of all neighbor vertices of the vertex
Implements SGL::AbstractGraph< T >.
Definition at line 227 of file AdjacencyMatrix.hpp.
{
     unsigned index;
     try {
         index = _index(p_v);
     } catch (const logic_error &le) {
         throw logic_error("vertexNeighborhood: the vertex isn't in the graph");
     }
     vector<T> neighbors;
     for (unsigned i = 0; i < m_elems.size(); i++) {
         if (m_matrix->hasEdge(index, i)) {
             neighbors.push_back(m_elems[i]);
         }
     }
     if (p_closed
             && std::find(neighbors.begin(), neighbors.end(), p_v)
                     == neighbors.end()) {
         neighbors.push_back(p_v);
     }
     return neighbors;
 }
template<typename T > unsigned SGL::Adjacency_Matrix< T >::vertexOutDegree (const T & p_v) const virtual
Returns the out-degree of a vertex in the graph, i.e.
the number of edges with other vertices it is the source of.
Parameters
[in] p_v the vertex we want to know the out-degree of
Precondition
The vertex must be in the graph
Exceptions
logic_error if the vertex isn't in the graph
Returns
the number of edges to other vertices the vertex is the source of
Implements SGL::AbstractGraph< T >.
Definition at line 162 of file AdjacencyMatrix.hpp.
References SGL::UNDIRECTED.
{
     unsigned index_s;
     unsigned outdegree = 0;
     try {
         index_s = _index(p_v);
     } catch (const logic_error &le) {
         throw logic_error("vertexOutDegree: the vertex isn't in the graph");
     }
     for (unsigned i = 0; i < m_elems.size(); i++) {
         if (m_matrix->hasEdge(index_s, i)) {
             outdegree++;
             if (i == index_s && (this->m_config & UNDIRECTED)) {
                 outdegree++;
             }
         }
     }
     return outdegree;
 }
template<typename T > vector< T > SGL::Adjacency_Matrix< T >::vertices () const virtual
Lists all the vertices in the graph Returns in a vector all the vertices of the graph.
Precondition
Enough memory available
Postcondition
A vector of all the vertices data is returned
Exceptions
bad_alloc in case of insufficient memory
Returns
a vector containing all the vertices of the graph
Implements SGL::AbstractGraph< T >.
Definition at line 349 of file AdjacencyMatrix.hpp.
Referenced by SGL::Adjacency_Matrix< T >::Adjacency_Matrix(), and SGL::Adjacency_Matrix< T >::operator==().
{
     vector<T> verts(m_elems);
     return verts;
 }
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & p_stream, const Adjacency_Matrix< T > & p_matrix) friend
Definition at line 91 of file AdjacencyMatrix.h.
 { p_stream << p_matrix._repr(); return p_stream; }
Member Data Documentation
template<typename T> std::vector<T> SGL::Adjacency_Matrix< T >::m_elems private
all the vertices
Definition at line 148 of file AdjacencyMatrix.h.
Referenced by SGL::Adjacency_Matrix< T >::operator=().
template<typename T> IMatrix* SGL::Adjacency_Matrix< T >::m_matrix private
the adjacency matrix itself
Definition at line 149 of file AdjacencyMatrix.h.
Referenced by SGL::Adjacency_Matrix< T >::UndirectedMatrix::_nbVertices(), SGL::Adjacency_Matrix< T >::DirectedMatrix::addEdge(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::addEdge(), SGL::Adjacency_Matrix< T >::DirectedMatrix::addVertex(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::addVertex(), SGL::Adjacency_Matrix< T >::Adjacency_Matrix(), SGL::Adjacency_Matrix< T >::DirectedMatrix::deleteEdge(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::deleteEdge(), SGL::Adjacency_Matrix< T >::DirectedMatrix::deleteVertex(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::deleteVertex(), SGL::Adjacency_Matrix< T >::DirectedMatrix::edges(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::edges(), SGL::Adjacency_Matrix< T >::DirectedMatrix::hasEdge(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::hasEdge(), SGL::Adjacency_Matrix< T >::nbEdges(), SGL::Adjacency_Matrix< T >::UndirectedMatrix::nbEdges(), SGL::Adjacency_Matrix< T >::operator=(), and SGL::Adjacency_Matrix< T >::~Adjacency_Matrix().
The documentation for this class was generated from the following files:
/home/baron_a/Projects/sgl/cpp/AdjacencyMatrix.h
/home/baron_a/Projects/sgl/cpp/AdjacencyMatrix.hpp