SGL (Simple Graph Library): SGL::Adjacency_List< T > Class Template Reference
SGL::Adjacency_List< T > Class Template Reference
#include <AdjacencyList.h>
Classes
class Node
Internal class of the list.
Public Member Functions
Adjacency_List (configuration p_flags=0)
Constructor.
Adjacency_List (const Adjacency_List &p_src)
Copy constructor.
Adjacency_List (const Adjacency_List &p_src, const std::vector< T > &p_filter)
Constructor of a sub-graph of the original, using a filter vector i.e.
~Adjacency_List ()
Destructor.
const Adjacency_List & operator= (const Adjacency_List &p_src)
Assignment operator overloading: deep copy of a graph.
bool vertexIsSource (const T &p_v) const
Tells if a vertex is a source (no edges coming to it = in-degree 0)
bool vertexIsSink (const T &p_v) const
Tells if a vertex is a sink (no edges starting from it = out-degree = 0)
unsigned int nbVertices () const
Returns the number of vertices in the list.
unsigned int order () const
Alias of the nbVertices method "order" is the mathematical term for "number of vertices".
unsigned int nbEdges () const
Returns the number of edges in the list.
unsigned int size () const
Alias of the nbEdges method "size" is the mathematical term for "number of edges" (not to be mistaken with order, the number of vertices)
bool hasVertex (const T &) const
verifies that a vertex is in the graph
unsigned int vertexInDegree (const T &) const
Returns the in-degree of a vertex in the graph i.e.
unsigned int vertexOutDegree (const T &) const
Returns the out-degree of a vertex in the graph, i.e.
std::vector< T > vertexNeighborhood (const T &, bool p_closed=false) const
Lists the adjacent vertices of a vertex in the graph.
bool hasEdge (const T &, const T &) const
verifies that an edge is in the graph
std::vector< T > vertices () const
Lists all the vertices in the graph Returns in a vector all the vertices of the graph.
std::vector< std::pair< T, T > > edges () const
Lists all the edges in the graph.
void addVertex (const T &)
Adds a vertex to the graph.
void deleteVertex (const T &)
deletes a vertex from the graph
void addEdge (const T &, const T &)
Adds an edge in the graph.
void deleteEdge (const T &, const T &)
Deletes an edge in the graph.
void display () const
bool equals (const Adjacency_List &p_g2) const
Checks the structural equality of two graphs: same vertices, same edges.
bool operator== (const Adjacency_List &p_g2)
Overloads the == operator to check structural equality of two graphs.
Public Member Functions inherited from SGL::AbstractGraph< T >
virtual ~AbstractGraph ()
bool equals (const AbstractGraph &p_other) const
Checks the structural equality of the current graph with another (same vertices, same edges)
bool operator== (const AbstractGraph &p_g2)
Overloads the == operator to check structural equality of two graphs.
Private Member Functions
void _copyAdjacencyList (const Adjacency_List &p_src)
Private function used by a copy constructor to copy the adjacency list of another graph.
int _index (const T &p_v) const
Private function used to retrieve the index in the intern adjacency list of an element.
const std::string _repr () const
Displays a representation of the graph.
Private Attributes
std::vector< Node * > m_nodes
Friends
std::ostream & operator<< (std::ostream &p_stream, const Adjacency_List &p_graph)
Additional Inherited Members
Protected Attributes inherited from SGL::AbstractGraph< T >
int m_config
Detailed Description
template<typename T>
class SGL::Adjacency_List< T >
Definition at line 20 of file AdjacencyList.h.
Constructor & Destructor Documentation
template<typename T > SGL::Adjacency_List< T >::Adjacency_List (configuration p_flags = 0) explicit
Constructor.
Precondition
Enough memory available
Parameters
[in] p_flags the configuration flags of the graph
Exceptions
bad_alloc in case of insufficient memory
Definition at line 20 of file AdjacencyList.hpp.
 {
 }
template<typename T > SGL::Adjacency_List< T >::Adjacency_List (const Adjacency_List< T > & p_src)
Copy constructor.
Precondition
Enough memory available
Parameters
[in] p_src the graph to copy
Exceptions
bad_alloc in case of insufficient memory
Definition at line 32 of file AdjacencyList.hpp.
 {
     _copyAdjacencyList(p_src);
 }
template<typename T > SGL::Adjacency_List< T >::Adjacency_List (const Adjacency_List< T > & p_src, const std::vector< T > & p_filter)
Constructor of a sub-graph of the original, using a filter vector i.e.
only the vertices contained in the vector will be copied
Parameters
[in] p_src the graph to copy
[in] p_filter the vector containing the vertices to copy
Precondition
Enough memory available
All the vertices in the filter vector must be in the source graph
Postcondition
a deep copy of the graph is obtained, with only the vertices contained in the filter vector
Exceptions
bad_alloc in case of insufficient memory
logic_error if a vertex in filter vector isn't contained in the source graph
Definition at line 49 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::hasVertex().
                                                                                            { // the explicit std:: is for Doxygen to recognize the function
     for (typename vector<T>::const_iterator vertex = p_filter.begin();
             vertex != p_filter.end(); ++vertex) {
         if (!p_src.hasVertex((*vertex))) {
             throw logic_error("Adjacency_List: a filter vector's vertex isn't in the source graph");
         }
         addVertex((*vertex));
     }
 }
template<typename T > SGL::Adjacency_List< T >::~Adjacency_List ()
Destructor.
Definition at line 63 of file AdjacencyList.hpp.
{
     for (unsigned int pos = 0; pos < m_nodes.size(); pos++) {
         delete m_nodes[pos];
     }
 }
Member Function Documentation
template<typename T > void SGL::Adjacency_List< T >::_copyAdjacencyList (const Adjacency_List< T > & p_src) private
Private function used by a copy constructor to copy the adjacency list of another graph.
Precondition
Enough memory available
Parameters
[in] p_src the source graph
Postcondition
The contents of the source graph (vertices and edges) are fully copied
Exceptions
bad_alloc in case of insufficient memory
Definition at line 428 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::Node::m_neighbors, SGL::Adjacency_List< T >::m_nodes, and SGL::Adjacency_List< T >::nbVertices().
{
     for (unsigned pos = 0; pos < p_src.nbVertices(); pos++) {
         addVertex(p_src.m_nodes[pos]->m_data);
     }
     for (unsigned pos = 0; pos < p_src.nbVertices(); pos++) {
         Node *cur = p_src.m_nodes[pos];
         for (typename list<T>::const_iterator v = cur->m_neighbors.begin();
                 v != cur->m_neighbors.end(); ++v) {
             addEdge(p_src.m_nodes[pos]->m_data, (*v));
         }
     }
 }
template<typename T > int SGL::Adjacency_List< T >::_index (const T & p_v) const private
Private function used to retrieve the index in the intern adjacency list of an element.
Precondition
The vertex is in the graph
Parameters
[in] p_v the vertex to search
Exceptions
logic_error the vertex isn't in the graph
Returns
the index in the adjacency list of the given vertex's node
Definition at line 450 of file AdjacencyList.hpp.
{
     int index = -1;
     for (unsigned int pos = 0; pos < m_nodes.size(); pos++) {
         if (m_nodes[pos]->m_data == p_v) {
             index = pos;
             break;
         }
     }
     if (index == -1) {
         throw logic_error("Vertex not in the graph");
     }
     return index;
 }
template<typename T > const std::string SGL::Adjacency_List< T >::_repr () const private virtual
Displays a representation of the graph.
Precondition
The type contained by the graph must have declared an overloading of the << operator for ostreams in order to be printed out by the function
Postcondition
The graph remains unchanged
Implements SGL::AbstractGraph< T >.
Definition at line 336 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::Node::m_data, and SGL::Adjacency_List< T >::Node::m_neighbors.
{
     stringstream stream;
     stream << "Number of vertices: " << nbVertices() << endl;
     stream << "Number of edges: " << nbEdges() << endl;
     stream << "List of vertices and their edges:" << endl << endl;
     for (unsigned int pos = 0; pos < m_nodes.size(); pos++) {
         Node *cur = m_nodes[pos];
         stream << "Vertex: " << cur->m_data << endl;
         stream << "Source of " << cur->m_neighbors.size() << " edges to vertices:"
                 << endl;
         for (typename list<T>::const_iterator v = cur->m_neighbors.begin();
                 v != cur->m_neighbors.end(); ++v) {
             stream << cur->m_data << " -> " << (*v);
             stream << endl;
         }
         if (cur->m_neighbors.size() == 0) {
             stream << "No edges" << endl;
         }
         stream << endl;
     }
     if (m_nodes.size() == 0) {
         stream << "Empty list" << endl;
     }
     return stream.str();
 }
template<typename T > void SGL::Adjacency_List< T >::addEdge (const T & p_v1, const T & p_v2) virtual
Adds an edge in the graph.
Parameters
[in] p_v1 the source vertex of the edge
[in] p_v2 the destination vertex of the edge
Precondition
Enough memory available
The 2 vertices of the edge are in the graph
Postcondition
The graph counts one more edge
Exceptions
bad_alloc in case of insufficient memory
logic_error if one of the two vertices isn't in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 115 of file AdjacencyList.hpp.
{
     int index_s1, index_s2;
     try {
         index_s1 = _index(p_v1);
         index_s2 = _index(p_v2);
     } catch (const logic_error &le) {
         throw logic_error("addEdge: one of the vertices isn't in the graph");
     }
     m_nodes[index_s1]->m_neighbors.push_back(m_nodes[index_s2]->m_data);
 }
template<typename T > void SGL::Adjacency_List< T >::addVertex (const T & p_v) virtual
Adds a vertex to the graph.
Parameters
[in] p_v the new element to put in the graph
Precondition
Enough memory available
The vertex isn't already in the graph
Postcondition
The graph counts one more vertex
Exceptions
bad_alloc in case of insufficient memory
logic_error if the vertex already is in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 95 of file AdjacencyList.hpp.
{
     if (hasVertex(p_v)) {
         throw logic_error("addVertex: this vertex is already in the graph");
     }
     Node *newv = new Node(p_v);
     m_nodes.push_back(newv);
 }
template<typename T > void SGL::Adjacency_List< T >::deleteEdge (const T & p_v1, const T & p_v2) virtual
Deletes an edge in the graph.
Parameters
[in] p_v1 the source vertex of the edge
[in] p_v2 the destination vertex of the edge
Precondition
The 2 vertices of the edge are in the graph
Postcondition
The graph counts one less edge
Exceptions
logic_error if one of the two vertices isn't in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 135 of file AdjacencyList.hpp.
{
     int index_s1, index_s2;
     try {
         index_s1 = _index(p_v1);
         index_s2 = _index(p_v2);
     } catch (const logic_error &le) {
         throw logic_error("deleteEdge: one of the vertices isn't in the graph");
     }
     if (!hasEdge(p_v1, p_v2)) {
         throw logic_error("deleteEdge: no edge between the two vertices");
     }
     m_nodes[index_s1]->m_neighbors.remove(m_nodes[index_s2]->m_data);
 }
template<typename T > void SGL::Adjacency_List< T >::deleteVertex (const T & p_v) virtual
deletes a vertex from the graph
Parameters
[in] p_v The element we want to delete the vertex of
Precondition
The vertex is in the graph
Postcondition
The graph counts one less vertex
Exceptions
logic_error if the vertex isn't in the graph
Implements SGL::AbstractGraph< T >.
Definition at line 157 of file AdjacencyList.hpp.
{
     int index_s;
     try {
         index_s = _index(p_v);
     } catch (const logic_error &le) {
         throw logic_error("deleteVertex: the vertex isn't in the graph");
     }
     for (unsigned int pos = 0; pos != m_nodes.size(); pos++) {
         m_nodes[pos]->m_neighbors.remove(m_nodes[index_s]->m_data);
     }
     delete m_nodes[index_s];
     m_nodes.erase(m_nodes.begin() + index_s);
 }
template<typename T> void SGL::Adjacency_List< T >::display () const
template<typename T > vector< pair< T, T > > SGL::Adjacency_List< T >::edges () const virtual
Lists all the edges in the graph.
Returns all the edges under the form of a vector of pair of elements (source, destination)
Precondition
Enough memory available
Postcondition
A vector of all the edges is returned
Exceptions
bad_alloc in case of insufficient memory
Returns
A vector of pairs of elements organized as (source, destination)
Implements SGL::AbstractGraph< T >.
Definition at line 373 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::Node::m_data, and SGL::Adjacency_List< T >::Node::m_neighbors.
Referenced by SGL::Adjacency_List< T >::nbEdges(), and SGL::Adjacency_List< T >::size().
{
     vector<pair<T, T> > edges;
     for (unsigned int i = 0; i < m_nodes.size(); i++) {
         Node *cur = m_nodes[i];
         for (typename list<T>::const_iterator v = cur->m_neighbors.begin();
                 v != cur->m_neighbors.end(); ++v) {
             edges.push_back(make_pair(cur->m_data, (*v)));
         }
     }
     return edges;
 }
template<typename T > bool SGL::Adjacency_List< T >::equals (const Adjacency_List< T > & p_g2) const
Checks the structural equality of two graphs: same vertices, same edges.
Parameters
[in] p_g2 the second graph
Returns
whether the two graphs are structurally equal or not
Definition at line 393 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::hasEdge(), SGL::Adjacency_List< T >::hasVertex(), SGL::Adjacency_List< T >::nbEdges(), and SGL::Adjacency_List< T >::nbVertices().
Referenced by SGL::Adjacency_List< T >::operator==().
{
     bool areEqual = true;
     if ((nbVertices() != p_g2.nbVertices()) || (nbEdges() != p_g2.nbEdges())) {
         areEqual = false;
     }
     if (areEqual) {
         std::vector<T> elems = vertices();
         for (unsigned int i = 0; i < elems.size(); i++) {
             if (!p_g2.hasVertex(elems[i])) {
                 areEqual = false;
                 break;
             }
         }
         std::vector<std::pair <T, T> > theEdges = edges();
         for (unsigned int i = 0; i < theEdges.size(); i++) {
             if (!p_g2.hasEdge(theEdges[i].first, theEdges[i].second)) {
                 areEqual = false;
                 break;
             }
         }
     }
     return areEqual;
 }
template<typename T > bool SGL::Adjacency_List< T >::hasEdge (const T & p_v1, const T & p_v2) const virtual
verifies that an edge is in the graph
Parameters
[in] p_v1 the source vertex of the edge
[in] p_v2 the destination vertex of the edge
Precondition
The 2 vertices of the edge are in the graph
Postcondition
The graph remains unchanged
Exceptions
logic_error if one of the two vertices isn't in the graph
Returns
whether the graph contains this edge or not
Implements SGL::AbstractGraph< T >.
Definition at line 200 of file AdjacencyList.hpp.
Referenced by SGL::Adjacency_List< T >::equals().
{
     bool isHere = true;
     int index_s1, index_s2;
     try {
         index_s1 = _index(p_v1);
         index_s2 = _index(p_v2);
     } catch (const logic_error &le) {
         throw logic_error("hasEdge: one of the vertices isn't in the graph");
     }
     if (std::find(m_nodes[index_s1]->m_neighbors.begin(),
             m_nodes[index_s1]->m_neighbors.end(), m_nodes[index_s2]->m_data)
             == m_nodes[index_s1]->m_neighbors.end()) {
         isHere = false;
     }
     return isHere;
 }
template<typename T > bool SGL::Adjacency_List< T >::hasVertex (const T & p_v) const virtual
verifies that a vertex is in the graph
Parameters
[in] p_v the element we search the vertex of
Postcondition
The graph remains unchanged
Returns
whether the graph contains this vertex or not
Implements SGL::AbstractGraph< T >.
Definition at line 179 of file AdjacencyList.hpp.
Referenced by SGL::Adjacency_List< T >::Adjacency_List(), and SGL::Adjacency_List< T >::equals().
{
     bool isHere = true;
     try {
         _index(p_v);
     } catch (const logic_error &le) {
         isHere = false;
     }
     return isHere;
 }
template<typename T> unsigned int SGL::Adjacency_List< T >::nbEdges () const inline virtual
Returns the number of edges in the list.
Returns
the number of edges in the list
Implements SGL::AbstractGraph< T >.
Definition at line 69 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::edges().
Referenced by SGL::Adjacency_List< T >::equals().
{
         return edges().size();
     }
template<typename T> unsigned int SGL::Adjacency_List< T >::nbVertices () const inline virtual
Returns the number of vertices in the list.
Returns
the number of vertices in the list
Implements SGL::AbstractGraph< T >.
Definition at line 52 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::m_nodes.
Referenced by SGL::Adjacency_List< T >::_copyAdjacencyList(), and SGL::Adjacency_List< T >::equals().
{
         return m_nodes.size();
     }
template<typename T > const Adjacency_List< T > & SGL::Adjacency_List< T >::operator= (const Adjacency_List< T > & p_src)
Assignment operator overloading: deep copy of a graph.
Parameters
[in] p_src the graph to copy
Precondition
Enough memory available
Postcondition
A deep copy is returned
Exceptions
bad_alloc in case of insufficient memory
Returns
the current graph returns itself
Definition at line 78 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::m_nodes.
{
     Adjacency_List<T> temp(p_src);
     std::swap(m_nodes, temp.m_nodes);
     return *this;
 }
template<typename T> bool SGL::Adjacency_List< T >::operator== (const Adjacency_List< T > & p_g2) inline
Overloads the == operator to check structural equality of two graphs.
Calls equals method.
Parameters
[in] p_g2 the second graph
Returns
whether the two lists are structurally equal or not
Definition at line 105 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::equals().
 { return equals(p_g2); }
template<typename T> unsigned int SGL::Adjacency_List< T >::order () const inline virtual
Alias of the nbVertices method "order" is the mathematical term for "number of vertices".
Returns
the number of vertices in the list
Implements SGL::AbstractGraph< T >.
Definition at line 61 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::m_nodes.
{
         return m_nodes.size();
     }
template<typename T> unsigned int SGL::Adjacency_List< T >::size () const inline virtual
Alias of the nbEdges method "size" is the mathematical term for "number of edges" (not to be mistaken with order, the number of vertices)
Returns
the number of edges in the list
Implements SGL::AbstractGraph< T >.
Definition at line 78 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::edges().
{
         return edges().size();
     }
template<typename T > unsigned int SGL::Adjacency_List< T >::vertexInDegree (const T & p_v) const virtual
Returns the in-degree of a vertex in the graph i.e.
the number of neighbor vertices of this vertex which have an edge that goes to it.
Parameters
[in] p_v the vertex we want to know the in-degree of
Precondition
The vertex has to be in the graph
Exceptions
logic_error if the vertex isn't in the graph
Returns
the number of edges to other vertices the vertex is the destination of
Implements SGL::AbstractGraph< T >.
Definition at line 247 of file AdjacencyList.hpp.
Referenced by SGL::Adjacency_List< T >::vertexIsSource().
{
     if (!hasVertex(p_v)) {
         throw logic_error("vertexInDegree: the vertex isn't in the graph");
     }
     unsigned int inDegree = 0;
     for (unsigned int pos = 0; pos < m_nodes.size(); pos++) {
         if (hasEdge(m_nodes[pos]->m_data, p_v)) {
             inDegree++;
         }
     }
     return inDegree;
 }
template<typename T> bool SGL::Adjacency_List< T >::vertexIsSink (const T & p_v) const inline virtual
Tells if a vertex is a sink (no edges starting from it = out-degree = 0)
Returns
(boolean) whether the vertex is a sink or not
Implements SGL::AbstractGraph< T >.
Definition at line 44 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::vertexOutDegree().
{
         return (vertexOutDegree(p_v) == 0);
     }
template<typename T> bool SGL::Adjacency_List< T >::vertexIsSource (const T & p_v) const inline virtual
Tells if a vertex is a source (no edges coming to it = in-degree 0)
Returns
(boolean) whether the vertex is a source or not
Implements SGL::AbstractGraph< T >.
Definition at line 36 of file AdjacencyList.h.
References SGL::Adjacency_List< T >::vertexInDegree().
{
         return (vertexInDegree(p_v) == 0);
     }
template<typename T > std::vector< T > SGL::Adjacency_List< T >::vertexNeighborhood (const T & p_v, bool p_closed = false) const virtual
Lists the adjacent vertices of a vertex in the graph.
If closed boolean is set to true, the vertex itself will be included in the returned neighborhood, making it a closed neighborhood (as opposed to the open version, without it included).
Parameters
[in] p_v the vertex we want the neighborhood of
[in] p_closed boolean to say whether we want the closed neighborhood of the vertex or not (false by default)
Precondition
Enough memory available
The vertex has to be in the graph
Exceptions
bad_alloc in case of insufficient memory
logic_error if the vertex isn't in the graph
Returns
A vector containing the data of all neighbor vertices of the vertex
Implements SGL::AbstractGraph< T >.
Definition at line 290 of file AdjacencyList.hpp.
References SGL::Adjacency_List< T >::Node::m_data, and SGL::Adjacency_List< T >::Node::m_neighbors.
{
     if (!hasVertex(p_v)) {
         throw logic_error("vertexNeighborhood: the vertex isn't in the graph");
     }
     vector<T> adjs;
     unsigned int index_v = _index(p_v);
     for (unsigned int pos = 0; pos < m_nodes.size(); pos++) {
         Node *cur = m_nodes[pos];
         if (pos == index_v) {
             // if we find the node of the given vertex, we add to the vector
             // all the vertices it points to, after having checked they're not already in it
             for (typename list<T>::const_iterator vert =
                     cur->m_neighbors.begin(); vert != cur->m_neighbors.end();
                     ++vert) {
                 if (std::find(adjs.begin(), adjs.end(), (*vert))
                         == adjs.end()) {
                     adjs.push_back((*vert));
                 }
             }
         } else {
             // for any other vertex, we check if the given vertex is one of the neighbors.
             // if it is, add this vertex to the vector after having checked it isn't already in it
             if (std::find(cur->m_neighbors.begin(), cur->m_neighbors.end(),
                     m_nodes[index_v]->m_data) != cur->m_neighbors.end()) {
                 if (std::find(adjs.begin(), adjs.end(), cur->m_data)
                         == adjs.end()) {
                     adjs.push_back(cur->m_data);
                 }
             }
         }
     }
     if (p_closed) {
         adjs.push_back(p_v);
     }
     return adjs;
 }
template<typename T > unsigned int SGL::Adjacency_List< T >::vertexOutDegree (const T & p_v) const virtual
Returns the out-degree of a vertex in the graph, i.e.
the number of edges with other vertices it is the source of.
Parameters
[in] p_v the vertex we want to know the out-degree of
Precondition
The vertex must be in the graph
Exceptions
logic_error if the vertex isn't in the graph
Returns
the number of edges to other vertices the vertex is the source of
Implements SGL::AbstractGraph< T >.
Definition at line 270 of file AdjacencyList.hpp.
Referenced by SGL::Adjacency_List< T >::vertexIsSink().
{
     if (!hasVertex(p_v)) {
         throw logic_error("vertexOutDegree: the vertex isn't in the graph");
     }
     return m_nodes[_index(p_v)]->m_neighbors.size();
 }
template<typename T > std::vector< T > SGL::Adjacency_List< T >::vertices () const virtual
Lists all the vertices in the graph Returns in a vector all the vertices of the graph.
Precondition
Enough memory available
Postcondition
A vector of all the vertices data is returned
Exceptions
bad_alloc in case of insufficient memory
Returns
a vector containing all the vertices of the graph
Implements SGL::AbstractGraph< T >.
Definition at line 227 of file AdjacencyList.hpp.
{
     vector<T> elems;
     elems.reserve(m_nodes.size());
     for (unsigned int pos = 0; pos < m_nodes.size(); pos++) {
         elems.push_back(m_nodes[pos]->m_data);
     }
     return elems;
 }
Friends And Related Function Documentation
template<typename T> std::ostream& operator<< (std::ostream & p_stream, const Adjacency_List< T > & p_graph) friend
Definition at line 108 of file AdjacencyList.h.
{
         p_stream << p_graph._repr();
         return p_stream;
     }
Member Data Documentation
template<typename T> std::vector<Node *> SGL::Adjacency_List< T >::m_nodes private
internal container for the adjacency list nodes
Definition at line 127 of file AdjacencyList.h.
Referenced by SGL::Adjacency_List< T >::_copyAdjacencyList(), SGL::Adjacency_List< T >::nbVertices(), SGL::Adjacency_List< T >::operator=(), and SGL::Adjacency_List< T >::order().
The documentation for this class was generated from the following files:
/home/baron_a/Projects/sgl/cpp/AdjacencyList.h
/home/baron_a/Projects/sgl/cpp/AdjacencyList.hpp